version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tsd_db
      POSTGRES_USER: tsd_user
      POSTGRES_PASSWORD: tsd_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tsd_user -d tsd_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://tsd_user:tsd_password@db:5432/tsd_db
      SECRET_KEY: your-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
